### PR TITLE
Use VCR for testing

### PR DESCRIPTION
**Pull request by davidcollom**
This allows for much better testing and less bandwidth during testing/expanding further models

### CODE REVIEW

**Comment by dhulihan** [comment]
Great idea to include VCR! This patch looks good, but you've included all the cassette data you've fetched during your tests, ie: `spec/vcr/.../[name of some test].yml`. 

Since cassettes are more of a local test asset, checking them into git creates a lot of commit noise, especially since there's a lot of binary data and requests usually change often over time. Could you add the cassette dir to `.gitignore`? 

Other than that, this looks great. Thanks!

**Comment by davidcollom** [comment]
Opps... I did want to leave the eBay one's in as these are time related and benefit more from VCR, but whats your thought on this?

**Comment by dhulihan** [comment]
Perfect, thanks! 

Yeah, let's leave the eBay one, since there's not really any permanent product pages on eBay. We'll have to update the cassette periodically in case eBay changes its page layout.

**Comment by davidcollom** [comment]
Travis Is still failing due to the updates within https://github.com/hulihanapplications/fletcher/pull/7 not being included at this stage of the branch

**Comment by dhulihan** [comment]
All pull requests should now be merged....still failing, let me see what I can do.

**Comment by dhulihan** [comment]
k, travis is passing, just had to add vcr to steam model. Fixed in c7ca026.

**Pull request merged**
