### PR TITLE
game.co.uk - Fletcher model

### PR DESCRIPTION
**Pull request by davidcollom**
Game.co.uk Integration

### CODE REVIEW

**Comment by dhulihan** [comment]
Got a merge conflict after merging your `googleproducts` branch, fixed manually & merged.

**Comment by davidcollom** [comment]
No problem, may want to update wiki page to reflect the 3 new models! :)

**Comment by dhulihan** [comment]
Indeed I shall. Thanks for the reminder.

**Comment by davidcollom** [comment]
Not a problem, just realised its an actual file (first time contributor), I have plenty of other sites to do if your interested.

**Pull request closed without merging**
